language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "schnatterer-github"
    
script:
  # Simple smoke test
  - docker build -t tomcat-reloading-connector-spring .
  - CONTAINER=$(docker run --rm -p8443:8443 -d tomcat-reloading-connector-spring)
  # Wait for container to be ready
  - wget -O- --retry-connrefused --tries=30 -q --wait=1 --no-check-certificate https://localhost:8443 &> /dev/null
  - BEFORE=$(echo | openssl s_client -showcerts -servername localhost -connect localhost:8443 2>/dev/null | openssl x509 -inform pem -noout -text | grep -A2 Validity)
  - docker exec -w /app ${CONTAINER} ./createCerts.sh
  - sleep 5
  - AFTER=$(echo | openssl s_client -showcerts -servername localhost -connect localhost:8443 2>/dev/null | openssl x509 -inform pem -noout -text | grep -A2 Validity)
  - '[[ "${BEFORE}" != "${AFTER}" ]]'
  # Print logs for debugging
  - docker logs ${CONTAINER}
  - docker stop ${CONTAINER}
  - docker build -t tomcat-reloading-connector --build-arg=FLAVOR=embedded-tomcat .
  - CONTAINER=$(docker run --rm -p8443:8443 -d tomcat-reloading-connector)
  - wget -O- --retry-connrefused --tries=30 -q --wait=1 --no-check-certificate https://localhost:8443 &> /dev/null
  # Fail for non positive return code
  - curl -k --fail https://localhost:8443
  - docker logs ${CONTAINER}
  - docker stop ${CONTAINER}

  # Maven deploy
  - |
    cat << EOF > settings.xml
    <settings>
      <servers>
        <server>
          <id>ossrh</id>
          <username>\${env.OSSRH_USER}</username>
          <password>\${env.OSSRH_TOKEN}</password>
        </server>
      </servers>
    </settings>
    EOF

  # This requires the following Env Vars defined in travis settings:
  # - OSSRH_USER - Access Token to Nexus
  # - OSSRH_TOKEN - Access Token to Nexus
  # - PGP_PASSPHRASE=literal:PASSPHRASE
  # - PK_BASE64 - Content of your PK, base64 encoded, create with e.g. "base64 -w0 pk.asc"
  - TMP_KEY="$(mktemp)"
  - echo "${PK_BASE64}" | base64 -d > "${TMP_KEY}"
  - export PGP_SECRETKEY="keyfile:${TMP_KEY}"
  # See https://kohsuke.org/pgp-maven-plugin
  # Once there unit tests, wrap "package" with the following
  # org.jacoco:jacoco-maven-plugin:prepare-agent \
  # org.jacoco:jacoco-maven-plugin:report \
  - |
    ./mvnw clean \
    -Prelease -s settings.xml \
    package \
    sonar:sonar \
    deploy

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'